# Generated by Django 3.0.3 on 2020-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200921_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default=' ', upload_to='pics'),
        ),
    ]
