# Generated by Django 3.0.3 on 2020-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200921_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
