# Generated by Django 3.0.3 on 2020-09-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='details',
        ),
        migrations.AddField(
            model_name='item',
            name='details1',
            field=models.CharField(default='N/A', max_length=5000),
        ),
        migrations.AddField(
            model_name='item',
            name='details2',
            field=models.CharField(default='N/A', max_length=5000),
        ),
        migrations.AddField(
            model_name='item',
            name='details3',
            field=models.CharField(default='N/A', max_length=5000),
        ),
    ]
